image: docker:stable

services:
- docker:dind

before_script:
- docker info
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build-docker:
  stage: build
  script:
  - docker build -t futeba-imagem .
  - docker tag futeba-imagem dmiranda83/futeba-imagem:latest
  - docker push dmiranda83/futeba-imagem:latest

build-project:
  stage: build
  tags:
  - executor-tarefas
  script:
  - echo "gala runner"