image: docker:stable

stages:
- pre-build
- build
- test
- deploy

build-docker:
  services:
  - docker:dind

  before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

  stage: pre-build
  script:
  - docker build -t futeba-imagem .
  - docker tag futeba-imagem dmiranda83/futeba-imagem:latest
  - docker push dmiranda83/futeba-imagem:latest

build-project:
  services:
  - docker:dind
  - mysql:5.7
  variables:
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret
    MYSQL_DATABASE: homestead
    MYSQL_ROOT_PASSWORD: secret

    DB_NAME: homestead
    DB_USER: homestead
    DB_PASSWORD: secret
    DB_PORT: '3306'

  stage: build
  tags:
  - executor-tarefas
  dependencies:
  - build-docker
  script:
  - echo "gala runner"