spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homestead?createDatabaseIfNotExist=true
    username: homestead
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace